# Generated by Django 3.1.5 on 2021-02-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_remove_classroom_students'),
        ('students', '0002_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='classrooms.classroom'),
            preserve_default=False,
        ),
    ]
