# Generated by Django 3.1.5 on 2021-02-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20210209_1218'),
        ('classrooms', '0003_remove_classroom_students'),
        ('students', '0003_student_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(to='classrooms.Classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='subjects.Subject'),
        ),
    ]
