# Generated by Django 3.1.5 on 2021-02-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_remove_classroom_subjects'),
        ('students', '0004_auto_20210209_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lactive_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classrooms.schoolyear'),
        ),
    ]
