# Generated by Django 3.1.5 on 2021-02-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_subject_teacher'),
        ('students', '0006_auto_20210209_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.student'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='grid',
            name='subjects',
        ),
        migrations.AddField(
            model_name='grid',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='subjects.Subject'),
        ),
    ]
