# Generated by Django 3.1.5 on 2021-02-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_subject_teacher'),
        ('students', '0007_auto_20210209_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='subjects',
        ),
        migrations.AddField(
            model_name='grid',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subjects.subject'),
        ),
    ]
