# Generated by Django 3.1.5 on 2021-02-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_subject_teacher'),
        ('students', '0008_auto_20210209_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_subjects', to='subjects.subject'),
        ),
    ]
