# Generated by Django 3.1.5 on 2021-02-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0001_initial'),
        ('students', '0009_auto_20210209_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grids.grid'),
        ),
        migrations.DeleteModel(
            name='Grid',
        ),
    ]
