# Generated by Django 3.1.5 on 2021-02-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_remove_classroom_subjects'),
        ('students', '0013_remove_student_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='classrooms.classroom'),
            preserve_default=False,
        ),
    ]
