# Generated by Django 3.1.5 on 2021-02-07 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('colegial', 'Colegial')], max_length=10)),
                ('shift', models.CharField(choices=[('matutinal', 'Matutinal'), ('vespertine', 'Vespertine'), ('nocturnal', 'Nocturnal')], max_length=10)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
        ),
    ]
