# Generated by Django 3.1.5 on 2021-02-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_remove_classroom_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subjects',
        ),
    ]
