# Generated by Django 3.1.5 on 2021-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_remove_classroom_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='identified',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
