# Generated by Django 3.1.5 on 2021-02-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_remove_subject_classroom'),
        ('classrooms', '0005_auto_20210209_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lective_year', models.CharField(choices=[('9', '9')], max_length=1)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
            ],
        ),
    ]
