# Generated by Django 3.1.5 on 2021-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_schoolyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyear',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='lective_year',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9)]),
        ),
    ]
