# Generated by Django 3.1.5 on 2021-02-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_auto_20210209_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='lective_year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
    ]
