# Generated by Django 3.1.5 on 2021-02-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_auto_20210209_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='type',
        ),
        migrations.AddField(
            model_name='classroom',
            name='school_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='classrooms.schoolyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='type',
            field=models.CharField(choices=[('primary', 'Primary'), ('colegial', 'Colegial')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='lective_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1),
        ),
    ]
