# Generated by Django 3.1.5 on 2021-02-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0010_classroom_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subjects',
        ),
    ]
