# Generated by Django 3.1.5 on 2021-02-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_student_grid'),
        ('grids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
    ]
