# Generated by Django 3.1.5 on 2021-02-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('exater', 'Exater'), ('humans', 'Humans'), ('biological', 'Biologial')], max_length=10)),
                ('description', models.TextField(max_length=250)),
                ('estudents', models.ManyToManyField(to='students.Student')),
                ('teacher', models.ManyToManyField(to='teachers.Teacher')),
            ],
        ),
    ]
