# Generated by Django 3.1.5 on 2021-02-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='estudents',
        ),
    ]
