# Generated by Django 3.1.5 on 2021-02-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_estudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('exater', 'Exater'), ('humans', 'Humans'), ('biological', 'Biological')], max_length=10),
        ),
    ]
