# Generated by Django 3.1.5 on 2021-02-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classroom',
        ),
    ]
