# Generated by Django 3.1.5 on 2021-02-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_auto_20210209_1816'),
        ('subjects', '0005_remove_subject_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='classrooms.schoolyear'),
            preserve_default=False,
        ),
    ]
