# Generated by Django 3.1.5 on 2021-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='situation',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('not confirmed', 'NOT confirmed')], default=1, max_length=13),
            preserve_default=False,
        ),
    ]
